### ISSUE TITLE
4 tests erros when validating build in rpm spec 

### ISSUE THREAD

**Issue by muayyad-alsadi** [Yelp/dumb-init#115] opened 2016-08-26 13:06 UTC
when I activated testing the build with

```
PATH=.:$PATH py.test tests/
```

I got

> 4 failed, 169 passed in 3.06 seconds

here is the full build logs

https://paste.fedoraproject.org/414308/22152031/

**Comment by muayyad-alsadi** [comment] 2016-08-26 13:06
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /builddir/build/BUILD/dumb-init-1.1.3, inifile: pytest.ini
collected 173 items
tests/child_processes_test.py ........................
tests/cli_test.py ......................................................................
tests/exit_status_test.py ..................................F...F...F...F.
tests/proxies_signals_test.py ..........................
tests/shell_background_test.py ....
tests/tty_test.py .
=================================== FAILURES ===================================
_________________ test_exit_status_terminated_by_signal[1-1-3] _________________
signal = 3
    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + 3)
E        +  where 0 = <subprocess.Popen object at 0x7feaa59c0790>.returncode
tests/exit_status_test.py:31: AssertionError
----------------------------- Captured stderr call -----------------------------
[dumb-init] Running in debug mode.
[dumb-init] Child spawned with PID 5951.
[dumb-init] setsid complete.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 5951 exited with exit status 0.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 0. Goodbye.
_________________ test_exit_status_terminated_by_signal[1-0-3] _________________
signal = 3
    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + 3)
E        +  where 0 = <subprocess.Popen object at 0x7feaa59d6190>.returncode
tests/exit_status_test.py:31: AssertionError
----------------------------- Captured stderr call -----------------------------
[dumb-init] Running in debug mode.
[dumb-init] Not running in setsid mode.
[dumb-init] Child spawned with PID 5959.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 5959 exited with exit status 0.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 0. Goodbye.
_________________ test_exit_status_terminated_by_signal[0-1-3] _________________
signal = 3
    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + 3)
E        +  where 0 = <subprocess.Popen object at 0x7feaa59c0850>.returncode
tests/exit_status_test.py:31: AssertionError
_________________ test_exit_status_terminated_by_signal[0-0-3] _________________
signal = 3
    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + 3)
E        +  where 0 = <subprocess.Popen object at 0x7feaa59d8b10>.returncode
tests/exit_status_test.py:31: AssertionError
===================== 4 failed, 169 passed in 3.06 seconds =====================
```

**Comment by muayyad-alsadi** [comment] 2016-08-26 13:07
are those errors from the restricted build environment, or debian specific assertions, ...etc.

should we fix the assertions or those 4 tests.

**Comment by chriskuehl** [comment] 2016-08-26 19:14
I can reproduce this:

```
ckuehl@debian:~$ docker run -ti fedora bash
[root@6ffe37019bfe /]# dnf install git gcc make glibc-static python3-pytest python3-mock
[root@6ffe37019bfe /]# git clone https://github.com/Yelp/dumb-init
Cloning into 'dumb-init'...
remote: Counting objects: 810, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 810 (delta 2), reused 0 (delta 0), pack-reused 800
Receiving objects: 100% (810/810), 164.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (462/462), done.
Checking connectivity... done.
[root@6ffe37019bfe /]# cd dumb-init
[root@6ffe37019bfe dumb-init]# make
cc -std=gnu99 -static -s -Wall -Werror -O3 -o dumb-init dumb-init.c
[root@6ffe37019bfe dumb-init]# PATH=.:$PATH py.test-3 tests/
================================== test session starts ===================================
platform linux -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /dumb-init, inifile: pytest.ini
collected 173 items

tests/child_processes_test.py ........................
tests/cli_test.py ......................................................................
tests/exit_status_test.py ..................................F...F...F...F.
tests/proxies_signals_test.py ..........................
tests/shell_background_test.py ....
tests/tty_test.py .

======================================== FAILURES ========================================
_______________ test_exit_status_terminated_by_signal[1-1-Signals.SIGQUIT] _______________

signal = <Signals.SIGQUIT: 3>

    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + <Signals.SIGQUIT: 3>)
E        +  where 0 = <subprocess.Popen object at 0x7f203d940550>.returncode

tests/exit_status_test.py:31: AssertionError
---------------------------------- Captured stderr call ----------------------------------
[dumb-init] Running in debug mode.
[dumb-init] Child spawned with PID 633.
[dumb-init] setsid complete.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 633 exited with exit status 0.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 0. Goodbye.
_______________ test_exit_status_terminated_by_signal[1-0-Signals.SIGQUIT] _______________

signal = <Signals.SIGQUIT: 3>

    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + <Signals.SIGQUIT: 3>)
E        +  where 0 = <subprocess.Popen object at 0x7f203d8cb320>.returncode

tests/exit_status_test.py:31: AssertionError
---------------------------------- Captured stderr call ----------------------------------
[dumb-init] Running in debug mode.
[dumb-init] Not running in setsid mode.
[dumb-init] Child spawned with PID 641.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 641 exited with exit status 0.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 0. Goodbye.
_______________ test_exit_status_terminated_by_signal[0-1-Signals.SIGQUIT] _______________

signal = <Signals.SIGQUIT: 3>

    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + <Signals.SIGQUIT: 3>)
E        +  where 0 = <subprocess.Popen object at 0x7f203d96b780>.returncode

tests/exit_status_test.py:31: AssertionError
_______________ test_exit_status_terminated_by_signal[0-0-Signals.SIGQUIT] _______________

signal = <Signals.SIGQUIT: 3>

    @pytest.mark.parametrize('signal', [
        signal.SIGTERM,
        signal.SIGINT,
        signal.SIGQUIT,
        signal.SIGKILL,
    ])
    @pytest.mark.usefixtures('both_debug_modes', 'both_setsid_modes')
    def test_exit_status_terminated_by_signal(signal):
        """dumb-init should exit with status 128 + signal when the child process is
        terminated by a signal.
        """
        proc = Popen(('dumb-init', 'sh', '-c', 'kill -{0} $$'.format(signal)))
        proc.wait()
>       assert proc.returncode == 128 + signal
E       assert 0 == (128 + <Signals.SIGQUIT: 3>)
E        +  where 0 = <subprocess.Popen object at 0x7f203d8cbd30>.returncode

tests/exit_status_test.py:31: AssertionError
========================== 4 failed, 169 passed in 5.26 seconds ==========================
```

**Comment by chriskuehl** [comment] 2016-08-26 19:22
Weird!

```
[root@6ffe37019bfe dumb-init]# ./dumb-init sh -c '/bin/kill -3 $$'; echo $?
131
[root@6ffe37019bfe dumb-init]# ./dumb-init sh -c 'kill -3 $$'; echo $?
0
```

`sh` is `bash` on Fedora but `dash` on Debian.

On Debian we can reproduce this by replacing `sh` with `bash`:

```
ckuehl@debian:~$ dumb-init bash -c 'kill -2 $$'; echo $?
130
ckuehl@debian:~$ dumb-init bash -c 'kill -3 $$'; echo $?
0
ckuehl@debian:~$ dumb-init bash -c 'kill -4 $$'; echo $?
132
```

**Comment by chriskuehl** [comment] 2016-08-26 20:37
(GitHub auto-closed the issue on merging the PR, can you test and reopen if it's still failing for you?)

**Comment by muayyad-alsadi** [comment] 2016-08-31 10:02
@chriskuehl 

would you please release this fix as v1.1.4

I noticed that you use python3, 

    PATH=.:$PATH py.test-3 tests/

fedora in general push for python-3, but fedora want to stick close to upstream (you), would please confirm that your "make test" would use python 3 so I can use in after building the package. because in my spec file I used python2

https://github.com/muayyad-alsadi/dumb-init/blob/rpm-spec-with-check/dumb-init.spec

**Comment by muayyad-alsadi** [comment] 2016-08-31 16:14
please re-open: testing on armv7hl architecture fails

https://kojipkgs.fedoraproject.org//work/tasks/2590/15452590/build.log

```
=================================== FAILURES ===================================
_____________ test_all_processes_receive_term_on_exit_if_setsid[1] _____________
    @pytest.mark.usefixtures('both_debug_modes', 'setsid_enabled')
    def test_all_processes_receive_term_on_exit_if_setsid():
        """If the child exits for some reason, dumb-init should send TERM to all
        processes in its session if setsid mode is enabled."""
>       child_pid, child_stdout = spawn_process_which_dies_with_children()
tests/child_processes_test.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/child_processes_test.py:95: in spawn_process_which_dies_with_children
    assert match, line
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
obj = b''
    def _format_assertmsg(obj):
        """Format the custom assertion message given.
    
        For strings this simply replaces newlines with '\n~' so that
        util.format_explanation() will preserve them instead of escaping
        newlines.  For other objects py.io.saferepr() is used first.
    
        """
        # reprlib appears to have a bug which means that if a string
        # contains a newline it gets escaped, however if an object has a
        # .__repr__() which contains newlines it does not get escaped.
        # However in either case we want to preserve the newline.
        if py.builtin._istext(obj) or py.builtin._isbytes(obj):
            s = obj
            is_repr = False
        else:
            s = py.io.saferepr(obj)
            is_repr = True
        if py.builtin._istext(s):
            t = py.builtin.text
        else:
            t = py.builtin.bytes
>       s = s.replace(t("\n"), t("\n~")).replace(t("%"), t("%%"))
E       TypeError: string argument without an encoding
/usr/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:394: TypeError
----------------------------- Captured stderr call -----------------------------
[dumb-init] Running in debug mode.
[dumb-init] Child spawned with PID 19601.
[dumb-init] setsid complete.
[dumb-init] Received signal 17.
[dumb-init] A child with PID 19601 exited with exit status 0.
[dumb-init] Forwarded signal 15 to children.
[dumb-init] Child exited with status 0. Goodbye.
_____________ test_all_processes_receive_term_on_exit_if_setsid[0] _____________
    @pytest.mark.usefixtures('both_debug_modes', 'setsid_enabled')
    def test_all_processes_receive_term_on_exit_if_setsid():
        """If the child exits for some reason, dumb-init should send TERM to all
        processes in its session if setsid mode is enabled."""
>       child_pid, child_stdout = spawn_process_which_dies_with_children()
tests/child_processes_test.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/child_processes_test.py:95: in spawn_process_which_dies_with_children
    assert match, line
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
obj = b''
    def _format_assertmsg(obj):
        """Format the custom assertion message given.
    
        For strings this simply replaces newlines with '\n~' so that
        util.format_explanation() will preserve them instead of escaping
        newlines.  For other objects py.io.saferepr() is used first.
    
        """
        # reprlib appears to have a bug which means that if a string
        # contains a newline it gets escaped, however if an object has a
        # .__repr__() which contains newlines it does not get escaped.
        # However in either case we want to preserve the newline.
        if py.builtin._istext(obj) or py.builtin._isbytes(obj):
            s = obj
            is_repr = False
        else:
            s = py.io.saferepr(obj)
            is_repr = True
        if py.builtin._istext(s):
            t = py.builtin.text
        else:
            t = py.builtin.bytes
>       s = s.replace(t("\n"), t("\n~")).replace(t("%"), t("%%"))
E       TypeError: string argument without an encoding
/usr/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:394: TypeError
==================== 2 failed, 171 passed in 21.36 seconds =====================
```

**Comment by chriskuehl** [comment] 2016-08-31 16:28
Is that test flaky or failing consistently?

We have no access to any armv7hl (or similar), so I don't know that we're going to be able to troubleshoot/fix this unfortunately. Is there any way to get access to those machines?

**Comment by chriskuehl** [comment] 2016-08-31 16:32
re: the other questions:

* We can't release 1.1.4 since there are no functionality changes, just tests. It'd be confused for people using dumb-init to have to bump the version for the same code. But I'll see if we can hurry the next release as there's a couple improvements I'd like to make.
* `make test` runs tox against python 2.6, 2.7, 3.4, and 3.5. This probably isn't very useful for Fedora tests; it would be better to use py.test directly with any of the versions above. Plus, tox will require internet access to download packages.

**Comment by muayyad-alsadi** [comment] 2016-09-01 07:01
> We can't release 1.1.4 since there are no functionality changes

no, problem, fedora allow merged upstream patches.

> python 2.6, 2.7, 3.4, and 3.5. 

thank you, so you as upstream maintain and test on both python-2 and python-3. I'll pick 3.

**Comment by muayyad-alsadi** [comment] 2016-09-01 08:11
> Is that test flaky or failing consistently?

it's consistantly failing, here is another build with same result.

https://kojipkgs.fedoraproject.org//work/tasks/553/15460553/build.log


BTW: the error above is a misleading it's bug in pytest

because `t=bytes` and `t("\n")` would result in error

```
>>> t=bytes
>>> t("\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string argument without an encoding
>>> t("\n", "utf-8")
b'\n'
```

but the actual error is from the assert, which means it failed the assert and tried to print format the assertion message then failed to build the assertion message.

maybe `atomic-devel` mailing list have people interesting in docker and arm.

https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2016-August/thread.html
https://lists.projectatomic.io/mailman/listinfo/atomic-devel

**Comment by muayyad-alsadi** [comment] 2016-09-01 08:59
when reverted to python2 the build succeeded even on armv7hl

https://kojipkgs.fedoraproject.org//work/tasks/965/15460965/build.log

please consider review your test on python3.

I you like either keep this ticket open to fix python3 on fedora on armv7hl
or open another one.

**Comment by chriskuehl** [comment] 2016-09-02 01:46
Cool, thanks for providing that extra info! That's really helpful. I'll close this ticket; I just opened #118 for the remaining issue.

FWIW we have noticed that same pytest bug internally in a lot of our traceback formatting -- pretty annoying :(

**Closed by chriskuehl** 2016-09-02 01:46 UTC
