### ISSUE TITLE
Making dumb-init-latest available

### ISSUE THREAD

**Issue by rberlich** [Yelp/dumb-init#77] opened 2016-05-20 10:02 UTC
Hi there,
the precompiled dumb-init Debian package is (at the time of writing) called dumb-init_1.0.2_amd64.deb, i.e. has a specific version number. This makes it difficult to pull the package from within a script, as the version number may change at any time. Would there be a chance to always add a package e.g. named dumb-init-latest ?
In any case thanks and best regards,
Beet

**Comment by asottile** [comment] 2016-05-20 14:43
Possible duplicate of #48

**Comment by chriskuehl** [comment] 2016-05-20 16:24
Yeah, unfortunately we couldn't come up with a good way to provide such URLs via GitHub.

You could script it if you wanted using their API, something like:

```bash
curl -s https://api.github.com/repos/Yelp/dumb-init/releases |
    awk -F\" '/browser_download_url": ".+_amd64"/ {print $4; exit}' |
    xargs curl -sLo /usr/bin/dumb-init --
```

If you know of a better way for us to provide a "latest" URL via GitHub, we'd be happy to do that, though!

**Closed by chriskuehl** 2016-05-20 16:24 UTC

**Comment by javabean** [comment] 2016-10-19 11:28
For reference, parsing GitHub json with [jq](https://stedolan.github.io/jq/):
```
	TAG_NAME="$(curl -fsSL https://api.github.com/repos/Yelp/dumb-init/releases/latest | jq --raw-output '.tag_name')"
	echo "Downloading dumb-init $TAG_NAME"
	curl -o /usr/local/sbin/dumb-init -fsSLR $(curl -fsSL https://api.github.com/repos/Yelp/dumb-init/releases/latest | jq --raw-output ".assets[] | select(.name == \"dumb-init_${TAG_NAME:1}_amd64\") | .browser_download_url")
```
